# Generated by Django 2.0.7 on 2019-07-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'managed': False},
        ),
    ]
