# Generated by Django 2.0.7 on 2019-07-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_auto_20190711_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
    ]
