# Generated by Django 2.0.7 on 2019-07-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0005_auto_20190711_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url_pic',
        ),
    ]
