# Generated by Django 2.0.7 on 2019-07-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0006_remove_banner_url_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'managed': False},
        ),
    ]
