# Generated by Django 2.0.7 on 2019-07-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0007_auto_20190712_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
