# Generated by Django 2.0.7 on 2019-07-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0009_article_new_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='insert_img',
        ),
    ]
