# Generated by Django 2.0.7 on 2019-08-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0010_remove_article_insert_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
    ]
