# Generated by Django 2.0.7 on 2019-08-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0011_auto_20190806_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
    ]
