# Generated by Django 2.0.7 on 2019-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0012_auto_20190806_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
