# Generated by Django 2.0.7 on 2019-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190712_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=28)),
                ('audio', models.FileField(upload_to='upload/audio')),
            ],
            options={
                'db_table': 't_caption',
            },
        ),
    ]
